variables:
  IMAGE_NAME: hub.ucloud.service.cn/leesin/my-probe
stages:
  - BuildImage
  - Deploy
build:
  stage: BuildImage
  tags:
  - k8s-runner
  image: hub.ucloudadmin.com/uaek/uaek-ciclient:latest
  script:
    - IMAGE_TAG=$CI_COMMIT_SHA && if [[ -n "$CI_COMMIT_TAG" ]]; then IMAGE_TAG=$CI_COMMIT_TAG ; fi
    - /kaniko/executor -c $CI_PROJECT_DIR -f Dockerfile -d $IMAGE_NAME:$IMAGE_TAG
deploy:
  stage: Deploy
  tags:
  - k8s-runner
  image: busybox:latest
  script:
    - IMAGE_TAG=$CI_COMMIT_SHA && if [[ -n "$CI_COMMIT_TAG" ]]; then IMAGE_TAG=$CI_COMMIT_TAG ; fi
    - cd $CI_PROJECT_DIR && sed -i "s#{{ .Image }}#$IMAGE_NAME:$IMAGE_TAG#" deploy.yml
    - wget  https://storage.googleapis.com/kubernetes-release/release/v1.14.7/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - mv kubectl /usr/bin
    - kubectl -n prj-install apply -f $CI_PROJECT_DIR/deploy.yaml